name: Publish
on:
  release:
    types: [published]
jobs:
  build-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Pack contents
        run: bun pm pack
      - name: Publish package
        run: bun publish ./*.tgz
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
